import { FaStar } from "react-icons/fa";
export const dataShop = [
    {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    },
    {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    }, {
        id: 1,
        img: "",
        category: "",
        title: "",
        del: "",
        price: "",
        start: <FaStar />,
        sexes: "",
        color: "",
        size: "",
    },

]